{% set version = "3.0.0" %}
{% set build_ext_version = version %}
{% set build_ext = "cuda" if build_type == 'cuda' else "cpu" %}
{% set proc_build_number = "1" %}
{% set checksum = "73c2cc3be537aa1f3fd9490cfec185714168c9bfd599d23e287ab0cc0558e27a" %}

package:
  name: arrow-cpp-ext
  version: {{ version }}

source:
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/apache-arrow-{{ version }}.tar.gz
  sha256: {{ checksum }}
  patches:
    # 03xx - patch temporary to fix a problem that when fixed upstream can be removed
    - 0300-ARROW-12917-C-Fix-handling-of-decimal-types-with-neg.patch
    # https://github.com/apache/arrow/pull/9569
    - 0301-fix-option-to-disable-TLS-verification.patch

build:
  number: 13
  run_exports:
    - {{ pin_subpackage("arrow-cpp", max_pin="x.x.x") }}

outputs:
  - name: arrow-cpp-proc
    version: {{ build_ext_version }}
    build:
      number: {{ proc_build_number }}
      string: {{ build_ext }}
    test:
      commands:
        - exit 0
    about:
      home: http://github.com/apache/arrow
      license: Apache-2.0
      license_file:
        - LICENSE.txt
      summary: 'A meta-package to select Arrow build variant'

  - name: arrow-cpp
    script: build-arrow.sh
    version: {{ version }}
    build:
      string: py{{ CONDA_PY}}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}{{ cudatoolkit | replace(".*", "") }} #[build_type == 'cuda']
      string: py{{ CONDA_PY}}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}  #[build_type == 'cpu']
{% if build_type == 'cuda' %}
      script_env:
        - CUDA_HOME
{% endif %}
      run_exports:
        - {{ pin_subpackage("arrow-cpp", max_pin="x.x.x") }}
      ignore_run_exports:
        - cudatoolkit
        - grpc-cpp
        - libprotobuf
        - zstd
        - orc
      track_features:
        {{ "- arrow-cuda" if build_type == 'cuda' else "" }}
    requirements:
      build:
        - abseil-cpp {{ abseil_cpp }} # [s390x]
        - libprotobuf {{ protobuf }}
        - grpc-cpp {{ grpc_cpp }}
        # to avoid https://gitlab.kitware.com/cmake/cmake/-/issues/18810
        - cmake 3.19        # [not s390x]
        - cmake {{ cmake }} # [s390x]
        - autoconf
        - ninja
        - make
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}
        - libstdcxx-ng {{ libstdcxx }}
      host:
        # Disable AWS S3 support
        #- aws-sdk-cpp
        - abseil-cpp {{ abseil_cpp }} # [s390x]
        - boost-cpp {{ boost }}
        - brotli
        - bzip2
        - c-ares
        - cudatoolkit {{ cudatoolkit }}    #[build_type == 'cuda']
        - gflags
        - glog
        - grpc-cpp {{ grpc_cpp }}
        - libprotobuf {{ protobuf }}
        - llvmdev 10  # [not s390x]
        - libutf8proc
        - lz4-c
        - numpy {{ numpy }}
        - orc 1.6.*
        - python {{ python }}
        - rapidjson
        - re2
        - snappy
        - thrift-cpp
        - zlib {{ zlib }}
        - zstd {{ zstd }}
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}
        - libstdcxx-ng {{ libstdcxx }}
      run:
        - brotli  # [s390x]
        - {{ pin_compatible('numpy', lower_bound='1.16') }}
        - cudatoolkit {{ cudatoolkit }}    #[build_type == 'cuda']
        - python {{ python }}
        - grpc-cpp {{ grpc_cpp }}
        - libprotobuf {{ protobuf }}
        - zstd {{ zstd }}
        - orc 1.6.*
        - libutf8proc  # [s390x]
      run_constrained:
        - arrow-cpp-proc * {{ build_ext }}

    about:
      home: http://github.com/apache/arrow
      license: Apache-2.0
      license_file:
        - LICENSE.txt
      summary: C++ libraries for Apache Arrow

    test:
      commands:
        # headers
        - test -f $PREFIX/include/arrow/api.h
        - test -f $PREFIX/include/arrow/flight/types.h
        - test -f $PREFIX/include/plasma/client.h
        # - test -f $PREFIX/include/gandiva/engine.h 
        - test -f $PREFIX/include/parquet/api/reader.h

        # shared
        - test -f $PREFIX/lib/libarrow${SHLIB_EXT}
        - test -f $PREFIX/lib/libarrow_dataset${SHLIB_EXT}
        - test -f $PREFIX/lib/libarrow_flight${SHLIB_EXT}
        - test -f $PREFIX/lib/libarrow_python${SHLIB_EXT}
        - test -f $PREFIX/lib/libparquet${SHLIB_EXT}
        - test -f $PREFIX/lib/libplasma${SHLIB_EXT}
        - test -f $PREFIX/lib/libarrow_cuda${SHLIB_EXT}    # [build_type == 'cuda']
        - test ! -f $PREFIX/lib/libarrow_cuda${SHLIB_EXT}  # [build_type != 'cuda']   

        # absence of static libraries
        - test ! -f $PREFIX/lib/libarrow.a
        - test ! -f $PREFIX/lib/libarrow_dataset.a
        - test ! -f $PREFIX/lib/libarrow_flight.a
        - test ! -f $PREFIX/lib/libarrow_python.a
        - test ! -f $PREFIX/lib/libplasma.a
        - test ! -f $PREFIX/lib/libparquet.a
        # - test ! -f $PREFIX/lib/libgandiva.a

        # conda tools
        - conda inspect linkages -p $PREFIX $PKG_NAME

  - name: pyarrow
    script: build-pyarrow.sh
    version: {{ version }}
    build:
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}{{ cudatoolkit | replace(".*", "") }} #[build_type == 'cuda']
      string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ build_ext }}  #[build_type == 'cpu']
{% if build_type == 'cuda' %}
      script_env:
        - CUDA_HOME
{% endif %}
      ignore_run_exports:
        - cudatoolkit
      track_features:
        {{ "- arrow-cuda" if build_type == 'cuda' else "" }}
    requirements:
      build:
        - cmake
        - ninja
        - make
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}
        - libstdcxx-ng {{ libstdcxx }}
      host:
        - {{ pin_subpackage('arrow-cpp', exact=True) }}
        - cudatoolkit {{ cudatoolkit }}  # [build_type == 'cuda']
        - cython
        - numpy {{ numpy }}
        - python {{ python }}
        - setuptools {{ setuptools }}
        - setuptools_scm 5.0.2
        - setuptools-scm 5.0.2
        - six {{ six }}
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}
        - libstdcxx-ng {{ libstdcxx }}
      run:
        - {{ pin_subpackage('arrow-cpp', exact=True) }}
        - {{ pin_compatible('numpy', lower_bound='1.16') }}
        - cudatoolkit {{ cudatoolkit }}  # [build_type == 'cuda']
        - python {{ python }}
      run_constrained:
        - arrow-cpp-proc * {{ build_ext }}

    about:
      home: http://github.com/apache/arrow
      license: Apache-2.0
      license_file:
        - LICENSE.txt
      summary: Python libraries for Apache Arrow

    test:
      imports:
        - pyarrow
        - pyarrow.dataset
        - pyarrow.flight
        - pyarrow.orc
        - pyarrow.parquet
        - pyarrow._hdfs
      commands:
        - test ! -f ${SP_DIR}/pyarrow/tests/test_array.py

about:
  home: http://github.com/apache/arrow
  license: Apache-2.0
  license_file:
    - LICENSE.txt
  summary: C++ and Python libraries for Apache Arrow

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

